Bleems.Dev.Test/Models/CategoryModel.cs
namespace Bleems.Dev.Test.Models
{
    public class CategoryModel
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}

Bleems.Dev.Test/Models/ProductModel.cs
namespace Bleems.Dev.Test.Models
{
    public class ProductModel
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductPhoto { get; set; }

    }
}

Bleems.Dev.Test/Models/ProductNewModel.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace Bleems.Dev.Test.Models
{
    public class ProductNewModel
    {
        [Required]
        public string ProductName { get; set; }
        [Required]
        public string ProductDescription { get; set; }
        [Required]
        public decimal ProductPrice { get; set; }
        [Required(ErrorMessage ="Choose Category")]
        public int ProductCategoryId { get; set; }
        public IFormFile ProductPhoto { get; set; }
    }
}

Bleems.Dev.Test/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Bleems.Dev.Test.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Bleems.Dev.Test/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bleems.Dev.Test.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Bleems.Dev.Test/Pages/NewProduct.cshtml.cs
using Bleems.Database;
using Bleems.Database.Models;
using Bleems.Dev.Test.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.IO;
using System.Threading.Tasks;

namespace Bleems.Dev.Test.Pages
{
    public class NewProductModel : PageModel
    {
        private readonly IProductsRepo productQuery;
        public NewProductModel(IProductsRepo _productQuery)
        {
            productQuery = _productQuery;

        }
        public async Task<IActionResult> OnPostAddProduct(ProductNewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (model.ProductPhoto.Length > 0)
                    {

                        if (model.ProductPhoto.Length >= 0.250 * 1024 * 1024)
                        {
                            ModelState.AddModelError("", "Please Select image smaller than 250/KB");
                            return Page();
                        }
                    }
                    string filePath = SaveProductPhoto(model.ProductPhoto);
                    string fileBase = $"{Request.Scheme}://{Request.Host}{Request.PathBase}";
                    await productQuery.AddNewProduct(new ProductAddModel()
                    {
                        ProductCategoryId = model.ProductCategoryId,
                        ProductName = model.ProductName,
                        ProductDescription = model.ProductDescription,
                        ProductPrice = model.ProductPrice,
                        ProductPhoto = filePath,
                        ProductFileUrlBase = fileBase
                    });


                    return RedirectToPage("Products");
                }
                catch (System.Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }

            }
            else
            {
                foreach (var value in ModelState.Values)
                {
                    foreach (var error in value.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.ErrorMessage);
                    }

                }
            }
            return Page();

        }

        private string SaveProductPhoto(IFormFile photoFile)
        {
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/productsPhotos");

            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);

            FileInfo fileInfo = new FileInfo(photoFile.FileName);
            string fileName = DateTime.Now.ToString("ddMMyyyyhhmmffff") + fileInfo.Extension;

            string fileNamePath = Path.Combine(path, fileName);

            using (var stream = new FileStream(fileNamePath, FileMode.Create))
            {
                photoFile.CopyTo(stream);
            }
            return "productsPhotos/" + fileName;
        }
    }
}

Bleems.Dev.Test/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bleems.Dev.Test.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Bleems.Dev.Test/Pages/Products.cshtml.cs
using Bleems.Database;
using Bleems.Database.Results;
using Bleems.Dev.Test.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bleems.Dev.Test.Pages
{
    public class ProductsModel : PageModel
    {
        private readonly IProductsRepo productQuery;
        public ProductsModel(IProductsRepo _productQuery)
        {
            productQuery = _productQuery;

        }

        [BindProperty]
        public ICollection<ProductModel> ProductsList { get; set; }

        //public IActionResult OnGetAllProducts()
        //{
        //    return ViewComponent("ProductList");
        //}
        public async Task<IActionResult> OnGetAllProducts()
        {
            ICollection<ProductResult> requests = await productQuery.GetAllProducts();
            var data = (from x in requests
                            select new ProductModel()
                            {
                                ProductId = x.ProductId,
                                ProductName = x.ProductName,
                                ProductPrice = x.ProductPrice,
                                ProductPhoto = x.ProductPhoto
                            }).ToList();
            return new JsonResult(data);
        }
        public async Task<IActionResult> OnGet()
        {
            ICollection<ProductResult> requests = await productQuery.GetAllProducts();
            ProductsList = (from x in requests
                            select new ProductModel()
                            {
                                ProductId = x.ProductId,
                                ProductName = x.ProductName,
                                ProductPrice = x.ProductPrice,
                                ProductPhoto = x.ProductPhoto
                            }).ToList();
            return Page();
        }

        public async Task<IActionResult> OnGetRemoveProduct( int productId)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Page();
                }

                if (productId == 0)
                    return Page();

                await productQuery.DeleteProduct(productId);

                return new JsonResult("Done");

            }
            catch (System.Exception ex)
            {
                return BadRequest(new { Message = ex.Message });
            }
        }

    }
}

Bleems.Dev.Test/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Bllems.Admin</a>.</p>
</div>

Bleems.Dev.Test/Pages/NewProduct.cshtml
@page
@model Bleems.Dev.Test.Pages.NewProductModel
@{
}

<form method="post" enctype = "multipart/form-data">
    @Html.AntiForgeryToken()
                        
    <div asp-validation-summary="All" class="text-danger"></div>


    <div class="card">
        <div class="card-header">
            <h3 class="card-title">ِNew Product</h3>
        </div>

        <div class="card-body">

            <div class="row">
                <div class="col-lg-3">
                    <div class="mb-5">
                        <div class="form-group">
                            <label for="ProductCategoryId">Choose Category</label>
                            <select class="form-control" name="ProductCategoryId">
                                <vc:Category-Drop-Down></vc:Category-Drop-Down>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-text">#</span>
                            <input name="ProductName" type="text" required class="form-control" placeholder="Name" aria-label="Product Name" />
                        </div>
                        
                        <div class="input-group">
                            <span class="input-group-text">#</span>
                            <input name="ProductDescription" required type="text" class="form-control" placeholder="Description" aria-label="Description" />
                        
                        </div>
                        
                        <div class="input-group">
                            <span class="input-group-text">$</span>
                            <input name="ProductPrice" required class="form-control" placeholder="Price" aria-label="Price" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="productPhoto">Photo</label>
                        <input type="file" required name="ProductPhoto" class="form-control-file" id="productPhoto">
                    </div>
                </div>

            </div>
    
            <div class="card-footer">
                <button class="btn btn-primary" asp-page-handler="AddProduct">Save</button>
            </div>
        </div>
    </div>
   

</form>

@section scripts{
    <partial name="_ValidationScriptsPartial" />
    }

Bleems.Dev.Test/Pages/Products.cshtml
@page
@model Bleems.Dev.Test.Pages.ProductsModel


<link href="~/lib/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
                        
 
                
<a asp-page="NewProduct"
   class="btn btn-sm btn-primary">New Product <i class="fas fa-arrow-left fs-4 me-2"></i></a>


<form method="post">
    @Html.AntiForgeryToken()
    <table id="productsTbl" class="table table-striped table-bordered nowrap" width="100%">
        <thead>
            <tr class="text-start fw-bolder fs-5 gs-0">
                <th class="w-10px pe-2">
                    #
                </th>
                <th class="min-w-125px">Name</th>
                <th class="min-w-125px">Price</th>
                <th class="min-w-125px">Photo</th>
                <th class="min-w-125px"></th>
            </tr>
        </thead>
        <tbody class="text-gray-600 fw-bold">
            @if (Model.ProductsList.Any())
            {
                foreach (var item in Model.ProductsList)
                {
                    <tr>
                        <td>
                        @Html.DisplayFor(x=> item.ProductId)
                    </td>
                    <td>
                        @Html.DisplayFor(x=> item.ProductName)
                    </td>
                    <td>
                        <div class="badge badge-lg badge-info">@item.ProductPrice</div>
                    </td>

                    <td>
                            @if (string.IsNullOrEmpty(item.ProductPhoto))
                            {
                                
                            }
                            else
                            {
                                <img src="~/@item.ProductPhoto"
                         height="100" width="100"
                         asp-append-version="true" />
                            }
                        
                    </td>
                    <td>

                        <a href='#' class='btn btn-warning' onclick=EditProduct(@item.ProductId);>Edit</a>
                        <a href='#' class='btn btn-danger' data-productid=@item.ProductId  onclick=DeleteProduct(this);>Delete</a>
                    </td>

                </tr>
            }
            }
         
        </tbody>
    </table>

</form>

@section Scripts
{
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <partial name="_ValidationScriptsPartial" />

    <script>
        $(document).ready(function() {
            $('.table').DataTable({
 
            });
      
        });
 

     
        var loadProducts = function() {
            var _url = "/Products?handler=AllProducts";
            var dest = document.getElementById("ProductSection");
            $.ajax({
                type: "Get",
                url: _url,
                asyn: true,
                success: function(result) {
                    $(dest).html("");
                    $(dest).html(result);
                    if (result != "") {
               
                    }
                }
            })
        };

        var DeleteProduct = (function(e) {
            var _url = "/Products?handler=RemoveProduct" ;
            var dest = document.getElementById("ProductSection");
            var productId = $(e).data("productid");

            $.ajax({
                type: "Get",
                url: _url,
                asyn: true,
                data: {"productId" : productId} ,
                headers: {
                    RequestVerificationToken:
                        $('input:hidden[name="__RequestVerificationToken"]').val()
                },
                success: function(result) {
                    showDone("Deleted");
                    var row = e.parentNode.parentNode;
                    row.parentNode.removeChild(row);
                }
                , error: function(xhr, status, error) {
                    var err = JSON.parse(xhr.responseText);
                    showError(error);
                }
            });
        });

    </script>
}
 

Bleems.Dev.Test/Pages/Shared/Components/CategoryDropDown/Default.cshtml
@model ICollection<Models.CategoryModel>

@*<option disabled selected hidden value="0">Choose Category</option>*@

@foreach (var item in Model.ToList())
{
    <option class="dropdown-item" value="@item.CategoryId">@item.CategoryName</option>
}

Bleems.Dev.Test/Pages/Shared/Components/ProductList/Default.cshtml
@model ICollection<Bleems.Dev.Test.Models.ProductModel>
@{}
 
  <table  id="productsTbl"  class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr class="text-start fw-bolder fs-5 gs-0">
                    <th class="w-10px pe-2">
                        #
                    </th>
                    <th class="min-w-125px">Name</th>
                    <th class="min-w-125px">Price</th>
                    <th class="min-w-125px">Photo</th>
                    <th class="min-w-125px"></th>
                    <th class="min-w-125px"></th>
                </tr>
            </thead>
            <tbody class="text-gray-600 fw-bold">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(x=> item.ProductId)
                        </td>
                        <td>
                            @Html.DisplayFor(x=> item.ProductName)
                        </td>
                        <td>
                            <div class="badge badge-lg badge-info">@item.ProductPrice</div>
                        </td>
                 
                        <td>
                            <img src="~/productsPhotos/@item.ProductPhoto" 
                            height="100" width="100" 
                            asp-append-version="true" /> 
                        </td>
                    
                
                    </tr>
                }
            </tbody>
        </table>

Bleems.Dev.Test/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bleems.Dev.Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Bleems.Dev.Test</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Products">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/NewProduct">New Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bleems.Dev.Test - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>